namespace DotAuth.Shared.Models;

using System.Net;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

///// <summary>
///// Defines the OAuth error type.
///// </summary>
//[DataContract]
//internal sealed class OauthError
//{
//    /// <summary>
//    /// Gets or sets the error.
//    /// </summary>
//    [DataMember] public string Error { get; set; } = null!;
//}

/// <summary>
/// A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
/// </summary>
public sealed record ErrorDetails
{
    /// <summary>
    /// A short, human-readable summary of the problem type.It SHOULD NOT change from occurrence to occurrence
    /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
    /// see[RFC7231], Section 3.4).
    /// </summary>
    [JsonPropertyName("error"), JsonRequired]
    public required string Title { get; set; }

    /// <summary>
    /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("status")]
    public HttpStatusCode Status { get; set; } = HttpStatusCode.BadRequest;

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("detail")]
    public required string Detail { get; set; }

    /// <inheritdoc />
    public override string ToString()
    {
        return $"{Title} - {Detail.Replace('\n', ' ').Replace("\r", string.Empty)} - {Status}";
    }
}
