<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>DotAuth Marten Stores</Description>
        <Title>DotAuth Marten Stores</Title>
        <AssemblyName>dotauth.stores.marten</AssemblyName>
        <PackageId>dotauth.stores.marten</PackageId>
        <RootNamespace>DotAuth.Stores.Marten</RootNamespace>
    </PropertyGroup>
    <PropertyGroup>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(PackageId).xml</DocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="marten"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\dotauth.shared\dotauth.shared.csproj"/>
    </ItemGroup>
</Project>
