<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
      <RootNamespace>DotAuth.Mcp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dotauth.shared\dotauth.shared.csproj" />
  </ItemGroup>

</Project>
