<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>DotAuth.Sms.Ui</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Areas\**\*.*" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Areas\**\*.*" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Areas\sms\Views\_ViewImports.cshtml" />
    </ItemGroup>

</Project>
