<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../shared.proj"/>
    <PropertyGroup>
        <RootNamespace>DotAuth.Uma.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
        <OutputType>exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="xunit.v3.mtp-v2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\dotauth.uma.web\dotauth.uma.web.csproj"/>
    </ItemGroup>

</Project>
