//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleAuth.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleAuth.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to address information..
        /// </summary>
        internal static string AccessToAddressInformation {
            get {
                return ResourceManager.GetString("AccessToAddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to email addresses..
        /// </summary>
        internal static string AccessToEmailAddresses {
            get {
                return ResourceManager.GetString("AccessToEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the OpenId scope..
        /// </summary>
        internal static string AccessToOpenIdScope {
            get {
                return ResourceManager.GetString("AccessToOpenIdScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to phone information..
        /// </summary>
        internal static string AccessToPhoneInformation {
            get {
                return ResourceManager.GetString("AccessToPhoneInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the profile information..
        /// </summary>
        internal static string AccessToProfileInformation {
            get {
                return ResourceManager.GetString("AccessToProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to your roles..
        /// </summary>
        internal static string AccessToRoles {
            get {
                return ResourceManager.GetString("AccessToRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an error {0} has been raised when trying to authenticate.
        /// </summary>
        internal static string AnErrorHasBeenRaisedWhenTryingToAuthenticate {
            get {
                return ResourceManager.GetString("AnErrorHasBeenRaisedWhenTryingToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one prompt parameter is not supported.
        /// </summary>
        internal static string AtLeastOnePromptIsNotSupported {
            get {
                return ResourceManager.GetString("AtLeastOnePromptIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one response_type parameter is not supported.
        /// </summary>
        internal static string AtLeastOneResponseTypeIsNotSupported {
            get {
                return ResourceManager.GetString("AtLeastOneResponseTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string Badrequest {
            get {
                return ResourceManager.GetString("Badrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client id parameter {0} doesn&apos;t exist or is not valid.
        /// </summary>
        internal static string ClientIsNotValid {
            get {
                return ResourceManager.GetString("ClientIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete client.
        /// </summary>
        internal static string CouldNotDeleteClient {
            get {
                return ResourceManager.GetString("CouldNotDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update approval for ticket {0}.
        /// </summary>
        internal static string CouldNotUpdateApproval {
            get {
                return ResourceManager.GetString("CouldNotUpdateApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource owner with same credentials already exists.
        /// </summary>
        internal static string DuplicateResourceOwner {
            get {
                return ResourceManager.GetString("DuplicateResourceOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate scopes {0} have been passed in parameter.
        /// </summary>
        internal static string DuplicateScopeValues {
            get {
                return ResourceManager.GetString("DuplicateScopeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add user.
        /// </summary>
        internal static string FailedToAddUser {
            get {
                return ResourceManager.GetString("FailedToAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing)..
        /// </summary>
        internal static string Http400 {
            get {
                return ResourceManager.GetString("Http400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP 401 Unauthorized client error status response code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource..
        /// </summary>
        internal static string Http401 {
            get {
                return ResourceManager.GetString("Http401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP 404 Not Found client error response code indicates that the server can&apos;t find the requested resource..
        /// </summary>
        internal static string Http404 {
            get {
                return ResourceManager.GetString("Http404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HyperText Transfer Protocol (HTTP) 500 Internal Server Error server error response code indicates that the server encountered an unexpected condition that prevented it from fulfilling the request..
        /// </summary>
        internal static string Http500 {
            get {
                return ResourceManager.GetString("Http500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier is missing.
        /// </summary>
        internal static string IdentifierIsMissing {
            get {
                return ResourceManager.GetString("IdentifierIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input missing.
        /// </summary>
        internal static string InputMissing {
            get {
                return ResourceManager.GetString("InputMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource.
        /// </summary>
        internal static string InvalidResource {
            get {
                return ResourceManager.GetString("InvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage server resources..
        /// </summary>
        internal static string ManageServerResources {
            get {
                return ResourceManager.GetString("ManageServerResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user managed resources and policies..
        /// </summary>
        internal static string ManageUma {
            get {
                return ResourceManager.GetString("ManageUma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameter {0} is missing.
        /// </summary>
        internal static string MissingParameter {
            get {
                return ResourceManager.GetString("MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no active AMR.
        /// </summary>
        internal static string NoActiveAmr {
            get {
                return ResourceManager.GetString("NoActiveAmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter in body request.
        /// </summary>
        internal static string NoParameterInBodyRequest {
            get {
                return ResourceManager.GetString("NoParameterInBodyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one of the request_uri is not valid.
        /// </summary>
        internal static string OneOfTheRequestUriIsNotValid {
            get {
                return ResourceManager.GetString("OneOfTheRequestUriIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one or more sector uri is not a redirect_uri.
        /// </summary>
        internal static string OneOrMoreSectorIdentifierUriIsNotARedirectUri {
            get {
                return ResourceManager.GetString("OneOrMoreSectorIdentifierUriIsNotARedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter in request body not valid.
        /// </summary>
        internal static string ParameterInRequestBodyIsNotValid {
            get {
                return ResourceManager.GetString("ParameterInRequestBodyIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameter {0} is not correct.
        /// </summary>
        internal static string ParameterIsNotCorrect {
            get {
                return ResourceManager.GetString("ParameterIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission request has been submitted..
        /// </summary>
        internal static string PermissionRequested {
            get {
                return ResourceManager.GetString("PermissionRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prompt parameter should have only none value.
        /// </summary>
        internal static string PromptParameterShouldHaveOnlyNoneValue {
            get {
                return ResourceManager.GetString("PromptParameterShouldHaveOnlyNoneValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the redirect url {0} doesn&apos;t exist or is not valid.
        /// </summary>
        internal static string RedirectUrlIsNotValid {
            get {
                return ResourceManager.GetString("RedirectUrlIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a client.
        /// </summary>
        internal static string RegisterAClient {
            get {
                return ResourceManager.GetString("RegisterAClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is not valid.
        /// </summary>
        internal static string RequestIsNotValid {
            get {
                return ResourceManager.GetString("RequestIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource cannot be updated.
        /// </summary>
        internal static string ResourceCannotBeUpdated {
            get {
                return ResourceManager.GetString("ResourceCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource owner credentials are not correct.
        /// </summary>
        internal static string ResourceOwnerCredentialsAreNotCorrect {
            get {
                return ResourceManager.GetString("ResourceOwnerCredentialsAreNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource owner credentials are not valid.
        /// </summary>
        internal static string ResourceOwnerCredentialsAreNotValid {
            get {
                return ResourceManager.GetString("ResourceOwnerCredentialsAreNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter resource_set_id needs to be specified.
        /// </summary>
        internal static string ResourceSetIdParameterNeedsToBeSpecified {
            get {
                return ResourceManager.GetString("ResourceSetIdParameterNeedsToBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the scopes {0} are not allowed or invalid.
        /// </summary>
        internal static string ScopesAreNotAllowedOrInvalid {
            get {
                return ResourceManager.GetString("ScopesAreNotAllowedOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the amr {0} doesn&apos;t exist.
        /// </summary>
        internal static string TheAmrDoesntExist {
            get {
                return ResourceManager.GetString("TheAmrDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authorization code has not been issued for the given client id {0}.
        /// </summary>
        internal static string TheAuthorizationCodeHasNotBeenIssuedForTheGivenClientId {
            get {
                return ResourceManager.GetString("TheAuthorizationCodeHasNotBeenIssuedForTheGivenClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authorization code is not correct.
        /// </summary>
        internal static string TheAuthorizationCodeIsNotCorrect {
            get {
                return ResourceManager.GetString("TheAuthorizationCodeIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authorization code is obsolete.
        /// </summary>
        internal static string TheAuthorizationCodeIsObsolete {
            get {
                return ResourceManager.GetString("TheAuthorizationCodeIsObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authorization flow is not supported.
        /// </summary>
        internal static string TheAuthorizationFlowIsNotSupported {
            get {
                return ResourceManager.GetString("TheAuthorizationFlowIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authorization policy is not satisfied.
        /// </summary>
        internal static string TheAuthorizationPolicyIsNotSatisfied {
            get {
                return ResourceManager.GetString("TheAuthorizationPolicyIsNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the authorization request cannot be processed because there is not valid prompt.
        /// </summary>
        internal static string TheAuthorizationRequestCannotBeProcessedBecauseThereIsNotValidPrompt {
            get {
                return ResourceManager.GetString("TheAuthorizationRequestCannotBeProcessedBecauseThereIsNotValidPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the claim {0} is not valid.
        /// </summary>
        internal static string TheClaimIsNotValid {
            get {
                return ResourceManager.GetString("TheClaimIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim must be specified.
        /// </summary>
        internal static string TheClaimMustBeSpecified {
            get {
                return ResourceManager.GetString("TheClaimMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the claims cannot be updated.
        /// </summary>
        internal static string TheClaimsCannotBeUpdated {
            get {
                return ResourceManager.GetString("TheClaimsCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client assertion is not a JWE token.
        /// </summary>
        internal static string TheClientAssertionIsNotAJweToken {
            get {
                return ResourceManager.GetString("TheClientAssertionIsNotAJweToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client assertion is not a JWS token.
        /// </summary>
        internal static string TheClientAssertionIsNotAJwsToken {
            get {
                return ResourceManager.GetString("TheClientAssertionIsNotAJwsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client cannot be authenticated with secret basic.
        /// </summary>
        internal static string TheClientCannotBeAuthenticatedWithSecretBasic {
            get {
                return ResourceManager.GetString("TheClientCannotBeAuthenticatedWithSecretBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client cannot be authenticated with secret post.
        /// </summary>
        internal static string TheClientCannotBeAuthenticatedWithSecretPost {
            get {
                return ResourceManager.GetString("TheClientCannotBeAuthenticatedWithSecretPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client cannot be authenticated with TLS.
        /// </summary>
        internal static string TheClientCannotBeAuthenticatedWithTls {
            get {
                return ResourceManager.GetString("TheClientCannotBeAuthenticatedWithTls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client {0} doesn&apos;t have a shared secret.
        /// </summary>
        internal static string TheClientDoesntContainASharedSecret {
            get {
                return ResourceManager.GetString("TheClientDoesntContainASharedSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client doesn&apos;t exist.
        /// </summary>
        internal static string TheClientDoesntExist {
            get {
                return ResourceManager.GetString("TheClientDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client {0} doesn&apos;t support the grant type {1}.
        /// </summary>
        internal static string TheClientDoesntSupportTheGrantType {
            get {
                return ResourceManager.GetString("TheClientDoesntSupportTheGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client &apos;{0}&apos; doesn&apos;t support the response type: &apos;{1}&apos;.
        /// </summary>
        internal static string TheClientDoesntSupportTheResponseType {
            get {
                return ResourceManager.GetString("TheClientDoesntSupportTheResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client id {0} doesn&apos;t exist.
        /// </summary>
        internal static string TheClientIdDoesntExist {
            get {
                return ResourceManager.GetString("TheClientIdDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the client {0} requires PKCE.
        /// </summary>
        internal static string TheClientRequiresPkce {
            get {
                return ResourceManager.GetString("TheClientRequiresPkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the code verifier is not correct.
        /// </summary>
        internal static string TheCodeVerifierIsNotCorrect {
            get {
                return ResourceManager.GetString("TheCodeVerifierIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation code cannot be saved.
        /// </summary>
        internal static string TheConfirmationCodeCannotBeSaved {
            get {
                return ResourceManager.GetString("TheConfirmationCodeCannotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation code must be specified.
        /// </summary>
        internal static string TheConfirmationCodeMustBeSpecified {
            get {
                return ResourceManager.GetString("TheConfirmationCodeMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consent cannot be deleted.
        /// </summary>
        internal static string TheConsentCannotBeDeleted {
            get {
                return ResourceManager.GetString("TheConsentCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the current authenticated user doesn&apos;t match with the identity token.
        /// </summary>
        internal static string TheCurrentAuthenticatedUserDoesntMatchWithTheIdentityToken {
            get {
                return ResourceManager.GetString("TheCurrentAuthenticatedUserDoesntMatchWithTheIdentityToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter rule &apos;{0}&apos; failed.
        /// </summary>
        internal static string TheFilterRuleFailed {
            get {
                return ResourceManager.GetString("TheFilterRuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier must be specified.
        /// </summary>
        internal static string TheIdentifierMustBeSpecified {
            get {
                return ResourceManager.GetString("TheIdentifierMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity token does not contain SimpleAuth in the audience.
        /// </summary>
        internal static string TheIdentityTokenDoesntContainSimpleAuthAsAudience {
            get {
                return ResourceManager.GetString("TheIdentityTokenDoesntContainSimpleAuthAsAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the id_token_hint parameter is not a valid token.
        /// </summary>
        internal static string TheIdTokenHintParameterIsNotAValidToken {
            get {
                return ResourceManager.GetString("TheIdTokenHintParameterIsNotAValidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the jws payload cannot be extracted.
        /// </summary>
        internal static string TheJwsPayloadCannotBeExtracted {
            get {
                return ResourceManager.GetString("TheJwsPayloadCannotBeExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameter id_token_encrypted_response_alg must be specified.
        /// </summary>
        internal static string TheParameterIsTokenEncryptedResponseAlgMustBeSpecified {
            get {
                return ResourceManager.GetString("TheParameterIsTokenEncryptedResponseAlgMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameter {0} needs to be specified.
        /// </summary>
        internal static string TheParameterNeedsToBeSpecified {
            get {
                return ResourceManager.GetString("TheParameterNeedsToBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameter request_object_encryption_alg must be specified.
        /// </summary>
        internal static string TheParameterRequestObjectEncryptionAlgMustBeSpecified {
            get {
                return ResourceManager.GetString("TheParameterRequestObjectEncryptionAlgMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameter userinfo_encrypted_response_alg must be specified.
        /// </summary>
        internal static string TheParameterUserInfoEncryptedResponseAlgMustBeSpecified {
            get {
                return ResourceManager.GetString("TheParameterUserInfoEncryptedResponseAlgMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the password cannot be updated.
        /// </summary>
        internal static string ThePasswordCannotBeUpdated {
            get {
                return ResourceManager.GetString("ThePasswordCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the prompt parameter {0} is not supported.
        /// </summary>
        internal static string ThePromptParameterIsNotSupported {
            get {
                return ResourceManager.GetString("ThePromptParameterIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on the RFC-3986 the redirection-uri is not well formed.
        /// </summary>
        internal static string TheRedirectionUriIsNotWellFormed {
            get {
                return ResourceManager.GetString("TheRedirectionUriIsNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the redirection url is not the same than the one passed in the authorization request.
        /// </summary>
        internal static string TheRedirectionUrlIsNotTheSame {
            get {
                return ResourceManager.GetString("TheRedirectionUrlIsNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redirect_uri {0} cannot contain fragment.
        /// </summary>
        internal static string TheRedirectUrlCannotContainsFragment {
            get {
                return ResourceManager.GetString("TheRedirectUrlCannotContainsFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the redirect_uri {0} is not well formed.
        /// </summary>
        internal static string TheRedirectUrlIsNotValid {
            get {
                return ResourceManager.GetString("TheRedirectUrlIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the refresh token can be used only by the same issuer.
        /// </summary>
        internal static string TheRefreshTokenCanBeUsedOnlyByTheSameIssuer {
            get {
                return ResourceManager.GetString("TheRefreshTokenCanBeUsedOnlyByTheSameIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the refresh token is not valid.
        /// </summary>
        internal static string TheRefreshTokenIsNotValid {
            get {
                return ResourceManager.GetString("TheRefreshTokenIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the request cannot be extracted from the cookie.
        /// </summary>
        internal static string TheRequestCannotBeExtractedFromTheCookie {
            get {
                return ResourceManager.GetString("TheRequestCannotBeExtractedFromTheCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the request downloaded from request URI is not valid.
        /// </summary>
        internal static string TheRequestDownloadedFromRequestUriIsNotValid {
            get {
                return ResourceManager.GetString("TheRequestDownloadedFromRequestUriIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the request parameter is not correct.
        /// </summary>
        internal static string TheRequestParameterIsNotCorrect {
            get {
                return ResourceManager.GetString("TheRequestParameterIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the request_uri parameter is not well formed.
        /// </summary>
        internal static string TheRequestUriParameterIsNotWellFormed {
            get {
                return ResourceManager.GetString("TheRequestUriParameterIsNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the resource owner cannot be removed.
        /// </summary>
        internal static string TheResourceOwnerCannotBeRemoved {
            get {
                return ResourceManager.GetString("TheResourceOwnerCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource owner credentials are not correct.
        /// </summary>
        internal static string TheResourceOwnerCredentialsAreNotCorrect {
            get {
                return ResourceManager.GetString("TheResourceOwnerCredentialsAreNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource set {0} doesn&apos;t exist.
        /// </summary>
        internal static string TheResourceSetDoesntExist {
            get {
                return ResourceManager.GetString("TheResourceSetDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the response cannot be generated because the resource owner needs to be authenticated.
        /// </summary>
        internal static string TheResponseCannotBeGeneratedBecauseResourceOwnerNeedsToBeAuthenticated {
            get {
                return ResourceManager.GetString("TheResponseCannotBeGeneratedBecauseResourceOwnerNeedsToBeAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource owner doesn&apos;t exist.
        /// </summary>
        internal static string TheRoDoesntExist {
            get {
                return ResourceManager.GetString("TheRoDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one or more scopes are not valid.
        /// </summary>
        internal static string TheScopeAreNotValid {
            get {
                return ResourceManager.GetString("TheScopeAreNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the scope &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string TheScopeDoesntExist {
            get {
                return ResourceManager.GetString("TheScopeDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the scope(s) need(s) to be specified.
        /// </summary>
        internal static string TheScopesNeedToBeSpecified {
            get {
                return ResourceManager.GetString("TheScopesNeedToBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the sector identifier uris cannot be retrieved.
        /// </summary>
        internal static string TheSectorIdentifierUrisCannotBeRetrieved {
            get {
                return ResourceManager.GetString("TheSectorIdentifierUrisCannotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the signature is not correct.
        /// </summary>
        internal static string TheSignatureIsNotCorrect {
            get {
                return ResourceManager.GetString("TheSignatureIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the subject cannot be retrieved.
        /// </summary>
        internal static string TheSubjectCannotBeRetrieved {
            get {
                return ResourceManager.GetString("TheSubjectCannotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ticket cannot be inserted.
        /// </summary>
        internal static string TheTicketCannotBeInserted {
            get {
                return ResourceManager.GetString("TheTicketCannotBeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ticket {0} doesn&apos;t exist.
        /// </summary>
        internal static string TheTicketDoesntExist {
            get {
                return ResourceManager.GetString("TheTicketDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ticket is expired.
        /// </summary>
        internal static string TheTicketIsExpired {
            get {
                return ResourceManager.GetString("TheTicketIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the token doesn&apos;t exist.
        /// </summary>
        internal static string TheTokenDoesntExist {
            get {
                return ResourceManager.GetString("TheTokenDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the token has not been issued for the given client id &apos;{0}&apos;.
        /// </summary>
        internal static string TheTokenHasNotBeenIssuedForTheGivenClientId {
            get {
                return ResourceManager.GetString("TheTokenHasNotBeenIssuedForTheGivenClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the token is expired.
        /// </summary>
        internal static string TheTokenIsExpired {
            get {
                return ResourceManager.GetString("TheTokenIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the token is not valid.
        /// </summary>
        internal static string TheTokenIsNotValid {
            get {
                return ResourceManager.GetString("TheTokenIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url is not well formed.
        /// </summary>
        internal static string TheUrlIsNotWellFormed {
            get {
                return ResourceManager.GetString("TheUrlIsNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user needs to be authenticated.
        /// </summary>
        internal static string TheUserNeedsToBeAuthenticated {
            get {
                return ResourceManager.GetString("TheUserNeedsToBeAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user needs to give his consent.
        /// </summary>
        internal static string TheUserNeedsToGiveHisConsent {
            get {
                return ResourceManager.GetString("TheUserNeedsToGiveHisConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two factor authentication cannot be performed.
        /// </summary>
        internal static string TwoFactorAuthenticationCannotBePerformed {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two factor authentication is not enabled.
        /// </summary>
        internal static string TwoFactorAuthenticationIsNotEnabled {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authenticator is not properly configured.
        /// </summary>
        internal static string TwoFactorNotProperlyConfigured {
            get {
                return ResourceManager.GetString("TwoFactorNotProperlyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
    }
}
