//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleAuth.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleAuth.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to address information..
        /// </summary>
        internal static string AccessToAddressInformation {
            get {
                return ResourceManager.GetString("AccessToAddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to email addresses..
        /// </summary>
        internal static string AccessToEmailAddresses {
            get {
                return ResourceManager.GetString("AccessToEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the OpenId scope..
        /// </summary>
        internal static string AccessToOpenIdScope {
            get {
                return ResourceManager.GetString("AccessToOpenIdScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to phone information..
        /// </summary>
        internal static string AccessToPhoneInformation {
            get {
                return ResourceManager.GetString("AccessToPhoneInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the profile information..
        /// </summary>
        internal static string AccessToProfileInformation {
            get {
                return ResourceManager.GetString("AccessToProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to your roles..
        /// </summary>
        internal static string AccessToRoles {
            get {
                return ResourceManager.GetString("AccessToRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string Badrequest {
            get {
                return ResourceManager.GetString("Badrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete client.
        /// </summary>
        internal static string CouldNotDeleteClient {
            get {
                return ResourceManager.GetString("CouldNotDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update approval for ticket {0}.
        /// </summary>
        internal static string CouldNotUpdateApproval {
            get {
                return ResourceManager.GetString("CouldNotUpdateApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource owner with same credentials already exists.
        /// </summary>
        internal static string DuplicateResourceOwner {
            get {
                return ResourceManager.GetString("DuplicateResourceOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add user.
        /// </summary>
        internal static string FailedToAddUser {
            get {
                return ResourceManager.GetString("FailedToAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing)..
        /// </summary>
        internal static string Http400 {
            get {
                return ResourceManager.GetString("Http400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP 401 Unauthorized client error status response code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource..
        /// </summary>
        internal static string Http401 {
            get {
                return ResourceManager.GetString("Http401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP 404 Not Found client error response code indicates that the server can&apos;t find the requested resource..
        /// </summary>
        internal static string Http404 {
            get {
                return ResourceManager.GetString("Http404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HyperText Transfer Protocol (HTTP) 500 Internal Server Error server error response code indicates that the server encountered an unexpected condition that prevented it from fulfilling the request..
        /// </summary>
        internal static string Http500 {
            get {
                return ResourceManager.GetString("Http500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier is missing.
        /// </summary>
        internal static string IdentifierIsMissing {
            get {
                return ResourceManager.GetString("IdentifierIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input missing.
        /// </summary>
        internal static string InputMissing {
            get {
                return ResourceManager.GetString("InputMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource.
        /// </summary>
        internal static string InvalidResource {
            get {
                return ResourceManager.GetString("InvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage server resources..
        /// </summary>
        internal static string ManageServerResources {
            get {
                return ResourceManager.GetString("ManageServerResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user managed resources and policies..
        /// </summary>
        internal static string ManageUma {
            get {
                return ResourceManager.GetString("ManageUma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter in body request.
        /// </summary>
        internal static string NoParameterInBodyRequest {
            get {
                return ResourceManager.GetString("NoParameterInBodyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter in request body not valid.
        /// </summary>
        internal static string ParameterInRequestBodyIsNotValid {
            get {
                return ResourceManager.GetString("ParameterInRequestBodyIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a client.
        /// </summary>
        internal static string RegisterAClient {
            get {
                return ResourceManager.GetString("RegisterAClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource cannot be updated.
        /// </summary>
        internal static string ResourceCannotBeUpdated {
            get {
                return ResourceManager.GetString("ResourceCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource owner credentials are not correct.
        /// </summary>
        internal static string ResourceOwnerCredentialsAreNotCorrect {
            get {
                return ResourceManager.GetString("ResourceOwnerCredentialsAreNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter resource_set_id needs to be specified.
        /// </summary>
        internal static string ResourceSetIdParameterNeedsToBeSpecified {
            get {
                return ResourceManager.GetString("ResourceSetIdParameterNeedsToBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim must be specified.
        /// </summary>
        internal static string TheClaimMustBeSpecified {
            get {
                return ResourceManager.GetString("TheClaimMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client id {0} doesn&apos;t exist.
        /// </summary>
        internal static string TheClientIdDoesntExist {
            get {
                return ResourceManager.GetString("TheClientIdDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation code must be specified.
        /// </summary>
        internal static string TheConfirmationCodeMustBeSpecified {
            get {
                return ResourceManager.GetString("TheConfirmationCodeMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consent cannot be deleted.
        /// </summary>
        internal static string TheConsentCannotBeDeleted {
            get {
                return ResourceManager.GetString("TheConsentCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter rule &apos;{0}&apos; failed.
        /// </summary>
        internal static string TheFilterRuleFailed {
            get {
                return ResourceManager.GetString("TheFilterRuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier must be specified.
        /// </summary>
        internal static string TheIdentifierMustBeSpecified {
            get {
                return ResourceManager.GetString("TheIdentifierMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authenticator is not properly configured.
        /// </summary>
        internal static string TwoFactorNotProperlyConfigured {
            get {
                return ResourceManager.GetString("TwoFactorNotProperlyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
    }
}
