using System.Runtime.CompilerServices;

[assembly:InternalsVisibleTo("simpleauth")]
[assembly:InternalsVisibleTo("simpleauth.authserver")]
[assembly:InternalsVisibleTo("simpleauth.awslambda")]
[assembly:InternalsVisibleTo("simpleauth.client")]
[assembly:InternalsVisibleTo("simpleauth.manager.client")]
[assembly:InternalsVisibleTo("simpleauth.sms")]
[assembly:InternalsVisibleTo("simpleauth.sms.tests")]
[assembly:InternalsVisibleTo("simpleauth.tests")]
[assembly:InternalsVisibleTo("simpleauth.acceptancetests")]
[assembly:InternalsVisibleTo("simpleauth.stores.marten.acceptancetests")]
[assembly:InternalsVisibleTo("simpleauth.uma.tests")]
[assembly:InternalsVisibleTo("simpleauth.server.tests")]
[assembly:InternalsVisibleTo("simpleauth.stores.marten")]
