<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../shared.proj"/>
    <PropertyGroup>
        <AssemblyName>dotauth.tests</AssemblyName>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <RootNamespace>DotAuth.Tests</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\..\.editorconfig" Link=".editorconfig"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="testCert.pfx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="MartinCostello.Logging.XUnit.v3"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Testcontainers.Redis"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\dotauth.sms\dotauth.sms.csproj"/>
        <ProjectReference Include="..\..\src\dotauth\dotauth.csproj"/>
        <ProjectReference Include="..\..\src\dotauth.stores.redis\dotauth.stores.redis.csproj"/>
    </ItemGroup>

</Project>
