<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>dotauth.tests</AssemblyName>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <RootNamespace>DotAuth.Tests</RootNamespace>
        <OutputType>exe</OutputType>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\..\.editorconfig" Link=".editorconfig"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="testCert.pfx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="MartinCostello.Logging.XUnit.v3"/>
        <PackageReference Include="Testcontainers.Redis"/>
        <PackageReference Include="xunit.v3.mtp-v2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\dotauth.sms\dotauth.sms.csproj"/>
        <ProjectReference Include="..\..\src\dotauth\dotauth.csproj"/>
        <ProjectReference Include="..\..\src\dotauth.stores.redis\dotauth.stores.redis.csproj"/>
    </ItemGroup>

</Project>
